language: haxe

haxe:
  - 3.1.3
  - 3.2.1

os:
  - linux
  - osx

sudo: false
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib

install:
  - haxelib install hxcpp
  - haxelib list

script:
  - pushd project
  - haxelib run hxcpp build.xml
  - haxelib run hxcpp build.xml -DHXCPP_M64
  - popd
  - haxelib dev hxudp .
  - haxe compile-cpp.hxml && ./bin/UdpTest