version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    - cinst haxe -version 3.1.3 -y
    - RefreshEnv
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install hxcpp > log.txt || type log.txt && cmd /C exit 1
    - haxelib list

build_script:
    - cd project
    - haxelib run hxcpp build.xml -DHXCPP_M32
    - haxelib run hxcpp build.xml -DHXCPP_M64
    - cd ..
    - haxelib dev hxudp .
    - haxe compile-cpp.hxml

test_script:
    - bin\UdpTest.exe